name: build and push docker image from the github action  

on:
  workflow_dispatch:
 
jobs:
    publish_image:
        runs-on: ubuntu-latest 
        
        steps: 
        - name: checkout code 
          uses: actions/checkout@v4 
        - name: Docker image build 
          run: |
                docker build -t ${{ secrets.DOCKER_HUB_USERNAME}}/docker-project-image-push:dev .
        - name: Docker push images to dockerhub 
          run: | 
               docker login -u ${{ secrets.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_TOKEN}}
               docker push ${{ secrets.DOCKER_HUB_USERNAME}}/docker-project-image-push:dev 
  


